### PR TITLE
Document Still Not Defined

### PR DESCRIPTION
**Pull request by bradybeck**
#### Issue: 
* Using https://github.com/zeit/next.js, with this fix https://github.com/bokuweb/re-bulma/pull/52, I'm still seeing: 
```
ReferenceError: document is not defined
    at Object.<anonymous> (/....../node_modules/re-bulma/lib/index.js:324:40)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/..../dist/components/layout/footer.js:31:16)
    at Module._compile (module.js:556:32)
```

#### Solution: 
* Do more of a brute force approach. 💪

### CODE REVIEW

**Comment by bradybeck** [comment]
@bokuweb 👀 

FYI: @paulohp

**Comment by bokuweb** [comment]
@bradybeck thanks for your report. What version are you using?

**Comment by bradybeck** [comment]
`"version": "0.2.2"`

**Comment by bradybeck** [comment]
`"version": "0.2.2"`

**Comment by bokuweb** [comment]
@bradybeck published as 0.2.3 🙇

**Pull request merged**
